// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijFl-xJ3NJqfLeRmC3HIdfAlBwy3oYqQ',
    appId: '1:797371290446:web:b9b76b886040b489e4041f',
    messagingSenderId: '797371290446',
    projectId: 'shop-app-4a2e2',
    authDomain: 'shop-app-4a2e2.firebaseapp.com',
    storageBucket: 'shop-app-4a2e2.firebasestorage.app',
    measurementId: 'G-GEQW0G0CBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVf4U-BKwBQIKgNzJmPM7c3PuDAc8pLPU',
    appId: '1:797371290446:android:d36971bc16e27158e4041f',
    messagingSenderId: '797371290446',
    projectId: 'shop-app-4a2e2',
    storageBucket: 'shop-app-4a2e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlBbdwHzoYHwTRoYnVDJIrFqvokoVW7y4',
    appId: '1:797371290446:ios:e423b01b64c1fbdde4041f',
    messagingSenderId: '797371290446',
    projectId: 'shop-app-4a2e2',
    storageBucket: 'shop-app-4a2e2.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlBbdwHzoYHwTRoYnVDJIrFqvokoVW7y4',
    appId: '1:797371290446:ios:e423b01b64c1fbdde4041f',
    messagingSenderId: '797371290446',
    projectId: 'shop-app-4a2e2',
    storageBucket: 'shop-app-4a2e2.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAijFl-xJ3NJqfLeRmC3HIdfAlBwy3oYqQ',
    appId: '1:797371290446:web:68416e1302917b9ce4041f',
    messagingSenderId: '797371290446',
    projectId: 'shop-app-4a2e2',
    authDomain: 'shop-app-4a2e2.firebaseapp.com',
    storageBucket: 'shop-app-4a2e2.firebasestorage.app',
    measurementId: 'G-8TQVXMKGRG',
  );
}
